name: tweetz
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http:
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  animated_text_kit: ^4.2.2
  firebase_auth: ^4.2.0
  google_sign_in: ^5.4.2
  provider: ^6.0.4
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  file_picker: ^5.2.3
  firebase_storage: ^11.0.7
  modal_progress_hud: ^0.1.3
  like_button: ^2.0.5
  video_player: ^2.4.9
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
